#dubbo:
#  scan:
#    base-packages: com.smart.cloud.auth
#  protocols:
#    dubbo:
#      name: dubbo
#      port: -1
#    rest:
#      name: rest
#      port: 9090
#      server: netty
#  registry:
##   The Spring Cloud Dubbo's registry extension
#    address: spring-cloud://localhost
##   The traditional Dubbo's registry
##   address: zookeeper://127.0.0.1:2181
