#dubbo:
#  scan:
#    base-packages: com.smart.cloud.smart.module.account
#  protocols:
#    dubbo:
#      name: dubbo
#      port: -1
#  registry:
#    address: spring-cloud://localhost


#smart:
#  dubbo:
#    name: abc123
